# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: core
description: ZironOS Server Atomic Variant

base-image: quay.io/fedora/fedora-coreos
image-version: stable

stages:
  - name: eza
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install eza"
  - name: yazi
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install yazi-fm"
modules:
  - from-file: common/files.yml
  - from-file: common/fonts.yml
  - from-file: common/packages/cli/base.yml
  - from-file: common/packages/tui.yml
  - type: copy
    from: eza
    src: /usr/local/bin/eza
    dest: /usr/bin/
  - type: copy
    from: yazi
    src: /usr/local/bin/yazi
    dest: /usr/bin/
  - type: rpm-ostree
    install:
      - cockpit
      - fuse-zip
  - type: systemd
    system:
      enabled:
        - cockpit.socket
        - rpm-ostreed-automatic.timer
        - sshd.socket
        - tailscaled.service
      disabled:
        - sshd.service
    user:
      enabled:
        - podman.socket
        - ssh-agent.socket
