# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: cosmic-atomic
description: Cosmic Atomic Edition of ZironOS

base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 42

stages:
  - name: eza
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install eza"
  - name: yazi
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install yazi-fm"

modules:
  - from-file: common/files.yml
  - from-file: common/packages/cli.yml
  - from-file: common/packages/tui.yml
  - from-file: common/packages/gui.yml
  - from-file: common/fonts.yml
  - type: rpm-ostree
    remove:
      - cosmic-player
