# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kde-atomic
description: KDE Atomic Edition of ZironOS

base-image: quay.io/fedora-ostree-desktops/kinoite 
image-version: 42

stages:
  - name: eza
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install eza"
modules:
  - from-file: common/files.yml
  - from-file: common/packages.yml
  - from-file: common/fonts.yml
  - type: rpm-ostree
    remove:
      - kwrite
      - kwrited
  - type: default-flatpaks
    notify: true
    user: 
      install: 
        - org.kde.kwrite
