# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kde-atomic
description: KDE Atomic Edition of ZironOS

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 42

stages:
  - name: rust
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install eza"

modules:
  - from-file: common/files.yml
  - from-file: common/fonts.yml
  - from-file: common/packages/cli.yml
  - from-file: common/packages/tui.yml
  - from-file: common/packages/gui.yml
  - type: copy
    from: rust
    src: /usr/local/cargo/bin/*
    dest: /usr/bin/
  - type: rpm-ostree
    install:
      - ksshaskpass
    remove:
      - kwrite
  - type: default-flatpaks
    configurations:
      - scope: user
        notify: true
        install:
          - org.kde.kwrite
