# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kde-atomic
description: KDE Atomic Edition of ZironOS

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 42

stages:
  - name: eza
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install eza"
  - name: yazi
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install yazi-fm"
modules:
  - from-file: common/files.yml
  - from-file: common/fonts.yml
  - from-file: common/packages/cli.yml
  - from-file: common/packages/tui.yml
  - from-file: common/packages/gui.yml
  - type: rpm-ostree
    remove:
      - kwrite
      - dnf5
      - dnf5-plugins
  - type: default-flatpaks
    notify: true
    user:
      install:
        - org.kde.kwrite
