# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: server
description: ZironOS Server Atomic Variant

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 42

stages:
  - name: eza
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install eza"
  - name: yazi
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - "cargo install yazi-fm"
modules:
  - from-file: common/files.yml
  - from-file: common/fonts.yml
  - from-file: common/packages/cli.yml
  - from-file: common/packages/tui.yml
  - type: script
    snippets:
      - ln -s /usr/lib/systemd/system/sshd.service /etc/systemd/system/multi-user.target.wants/sshd.service
