# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
modules:
  - type: rpm-ostree
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - autojump
      - bat
      - duf
      - fastfetch
      # Hardware Checking
      - lshw
      - podman-compose
      - procs
      - ripgrep
      - tailscale
      - waypipe
      - zoxide
      - ffmpeg
    remove:
      - dnf5
      - nano
      - nano-default-editor
      - ffmpeg-free
