# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
modules:
  - type: script
    snippets:
      - "curl -o /tmp/tailscale.install https://tailscale.com/install.sh"
      - "chmod +x /tmp/tailscale.install"
      - "/tmp/tailscale.install"
  - type: rpm-ostree
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
  - type: script
    snippets:
      - dnf install -y --allowerasing ffmpeg
  - type: rpm-ostree
    install:
      - autojump
      - bat
      - duf
      - fastfetch
      # Hardware Checking
      - lshw
      - podman-compose
      - procs
      - ripgrep
      - waypipe
      - zoxide
    remove:
      - dnf5
      - nano
      - nano-default-editor
