name: Ziron Build 
on:
  schedule:
    - cron:
        "00 06 * * *"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ziron-build:
    name: Build Ziron Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - kinoite.yml 
    steps:
      - name: Build and Publish
        uses: blue-build/github-action@v1.8
        if: github.event_name != 'pull_request'
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: true
          build_opts: --compression-format zstd

          maximize_build_space: true
